# Generated by Django 6.0.3 on 2026-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('gender', models.CharField()),
                ('age', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('BGroup', models.CharField()),
                ('state', models.CharField()),
                ('city', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
    ]
